apiVersion: v1
kind: Service
metadata:
  name: aplicacion-service
spec:
  selector:
    app: aplicacion
  ports:
    - protocol: TCP
      port: 3050    # Puerto en el Service
      targetPort: 3050  # Puerto donde corre la app en el contenedor
  type: LoadBalancer  # Cambia a NodePort si usas Minikube
