apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion
spec:
  replicas: 2  # Número de instancias
  selector:
    matchLabels:
      app: aplicacion
  template:
    metadata:
      labels:
        app: aplicacion
    spec:
      containers:
      - name: aplicacion
        image: aplicacion:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3050
        envFrom:
        - configMapRef:
            name: aplicacion-config
        - secretRef:
            name: aplicacion-secret
